apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: bussindex
build:
  artifacts:
  - image: bussindexapi
    context: api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
  helm:
    releases:
    - name: bussindexdb
      chartPath: equinor-charts/neo4j-community
      remote: true
      valuesFiles: ["./helm/neo4j/values.yaml"]
